# Introduction to Python

## Python Lists vs MATLAB Arrays
In MATLAB, everything is essentially a matrix. In Python, we have lists (general-purpose containers) and NumPy arrays (optimized for numerical computing).

Let's see how they behave differently.


In [ ]:
# Import Library
import numpy as np

In [ ]:
# Python List vs NumPy Array

# Python List
py_list = [1, 2, 3, 4]
print("Python list:", py_list)

Python list: [1, 2, 3, 4]


In [ ]:
# NumPy Array
np_array = np.array([1, 2, 3, 4])
print("NumPy array:", np_array)

NumPy array: [1 2 3 4]


In [ ]:
# List doesn't support element-wise operations directly
try:
    print(py_list * 2)
except Exception as e:
    print("Error:", e)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
# NumPy supports vectorized operations
print(np_array * 2)

[2 4 6 8]


### Heterogeneous data vs Numeric only
Python lists can store mixed data types. NumPy arrays are homogeneous.

In [ ]:
# Mixed data in Python list
mixed_list = [1, "two", 3.0, True]
print(mixed_list)

[1, 'two', 3.0, True]


In [ ]:
# NumPy tries to convert all to a common type
mixed_array = np.array([1, "two", 3.0, True])
print(mixed_array)

['1' 'two' '3.0' 'True']


### Indexing in NumPy Arrays (1D, 2D, 3D)

Indexing is 0-based in Python. Let's explore 1D, 2D, and 3D arrays.

In [ ]:
# 1D Array
a = np.array([10, 20, 30, 40, 50])
print(a[0], a[-1])   # first and last elements

10 50


In [ ]:
# 2D Array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("b:")
print(b)
print("b[0,0]: ", b[0,0]) # element at (0,0)
print("b[1,2]: ", b[1,2]) # element at (1,2)

b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0,0]:  1
b[1,2]:  6


In [ ]:
# 3D Array
c = np.arange(2*3*4).reshape(2,3,4)
print(c)
print(c[0,1,2])  # accessing 3D element

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
6


### Advanced Indexing and Slicing
NumPy slicing is very powerful.

In [ ]:
print(b[:, 1])     # column 1

[2 5 8]


In [ ]:
print(b[1, :])     # row 1

[4 5 6]


In [ ]:
print(c[1, :, :])  # slice whole 2D plane from 3D

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(c[:, :, 0])  # all first columns from each 2D layer

[[ 0  4  8]
 [12 16 20]]


## Conditional Statements

### If-Else in Python
Use indentation carefully. Let's try examples.

In [ ]:
x = 0.1
if x > 0:
    print("Positive")
elif x == 0:
    print("Zero")
else:
    print("Negative")


In [ ]:
score = 82
if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
else:
    grade = 'F'
print("Grade:", grade)


## Function Basics

In [ ]:
def greet(name):
    return f"Hello, {name}!"

In [ ]:
print(greet("Ali"))

In [ ]:
def stats(numbers=[1,2,3]):
    mean = sum(numbers)/len(numbers)
    return min(numbers), mean, max(numbers)


In [ ]:
low, avg, high = stats()
print(low, avg, high)

## Plotting in Python

### Basic Line Plot
We can plot mathematical functions easily.  
Let's plot sine and cosine on the same graph with labels and grid.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(0, 2*np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)

plt.figure(figsize=(6,4))
plt.plot(x, y1, label='sin(x)', color='blue', linestyle='--')
plt.plot(x, y2, label='cos(x)', color='red', linestyle='-.')
plt.title("Sine and Cosine Waves")
plt.xlabel("x")
plt.ylabel("Value")
plt.legend()
plt.grid(True)
plt.show()

### Scatter Plot
Used to visualize relationships between variables.  
We’ll color points based on their value.

In [ ]:
np.random.seed(0)
x = np.random.rand(50)
y = np.random.rand(50)
colors = x + y  # color based on sum
sizes = 300 * (x**2 + y**2)

plt.figure(figsize=(5,5))
plt.scatter(x, y, c=colors, s=sizes, alpha=0.6, cmap='viridis')
plt.title("Random Scatter Plot")
plt.xlabel("X")
plt.ylabel("Y")
plt.colorbar(label='x + y')
plt.show()


### Bar Chart
Bar charts are great for comparing categories.

In [ ]:
categories = ['Python', 'MATLAB', 'C++', 'Java']
students = [50, 20, 15, 10]

plt.figure(figsize=(6,4))
plt.bar(categories, students, color='skyblue', edgecolor='black')
plt.title("Favorite Programming Languages")
plt.ylabel("Number of Students")
plt.show()


### Histogram
Histograms show the distribution of numerical data.

In [ ]:
data = np.random.normal(0, 1, 1000)

plt.figure(figsize=(6,4))
plt.hist(data, bins=10, color='lightgreen', edgecolor='black', alpha=0.7)
plt.title("Histogram of Normally Distributed Data")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()


### Pie Chart
Pie charts show proportions between categories.

In [ ]:
sizes = [40, 25, 20, 15]
labels = ['AI', 'Robotics', 'Signal Processing', 'Embedded']
explode = (0.1, 0, 0, 0)

plt.figure(figsize=(5,5))
plt.pie(sizes, labels=labels, autopct='%1.1f%%', explode=explode, shadow=True)
plt.title("Interests of Electrical Engineering Students")
plt.show()


### 3D Surface Plot
We can create 3D plots to visualize mathematical functions.

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(6,5))
ax = fig.add_subplot(111, projection='3d')

X = np.linspace(-5, 5, 100)
Y = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(X, Y)
Z = np.sin(np.sqrt(X**2 + Y**2))

surf = ax.plot_surface(X, Y, Z, cmap='plasma', edgecolor='none')
ax.set_title('3D Surface Plot: z = sin(sqrt(x^2 + y^2))')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
fig.colorbar(surf, shrink=0.5, aspect=5)
plt.show()


## Uploading Custom Data

### Upload Files in Colab
Use the files module to upload from local machine.

In [ ]:
from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
    print("Uploaded:", filename)


### Navigating File System

In [ ]:
!pwd       # print working directory

In [ ]:
!ls  # list files

In [ ]:
%cd sample_data

In [ ]:
!ls

In [ ]:
%cd ..

In [ ]:
!mkdir data_folder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
